### ISSUE TITLE
Data sorting method error

### ISSUE THREAD

**Issue by dukechain2333** [cloudy-sfu/SLU-Daily-Report#3]
The administrator of Daily Report System reported that the reports of SLU-Daily-Report system's users have something wrong with their data sorting which causes failure reporting.

**Comment by cloudy-sfu** [comment]
Fix:
https://github.com/cloudy-sfu/SLU-Daily-Report/commit/80065eca54c33a6aa419dedecc90f9453a0bc694

These problems still exist:

In the POST body, the `boId` and `boDefId` fields are absent, but their values are hard to acquire. I cannot decide whether keep them absent or assign them empty strings is better.

The value of `SORTNUM` in `form_data` is hard to decide, because:
- In one account on Pudong campus, it is `SORTNUM=29`, a fixed value.
- In one account on Songjiang campus, it is `SORTNUM=28`, a fixed value.
And, no other account has been tested.

**Comment by cloudy-sfu** [comment]
Haven't received responses for a long time.
